estimator: raft_jax
estimate_type: flow
config:
  jit: true
  patch_size: 32
  patch_stride: 8
  hidden_dim: 128
  context_dim: 128
  corr_levels: 4
  corr_radius: 4
  iters: 12
  patches_groups: 29 # faster value found empirically is 29, it's the square root of the number of all patches (841)
  norm_fn: instance
  dropout: 0.0
  train: false
  gamma: 0.8
  use_temporal_propagation: false
  optimizer_config:
    name: adam
    learning_rate:
        schedule:
            name: constant
            value: 0.0001
    chain:
        - name: clip_by_global_norm
          kwargs: {max_norm: 1.0}
  out_dir: output
load_from: output/RaftJaxEstimator-from-torch.pkl
