REPETITIONS: 5
EXECUTIONS_POST_PROCESS: 100
EXECUTIONS_SAMPLE_PATCH: 1000
EXECUTIONS_COMPUTE_FLOW_LEVEL: 100
EXECUTIONS_BUILD_PYRAMID: 1000
EXECUTIONS_FLOW_BETWEEN: 100
EXECUTIONS_ESTIMATE_DIS_FLOW: 100
EXECUTIONS_DENSIFY: 1000
EXECUTIONS_EXTRACT_PATCHES_GRAD_HESS: 1000
EXECUTIONS_QUERY_FLOW_AT_POINTS: 1000
