dis_algorithms:
- name: DIS0
  parameters: {patch_size: 21, patch_stride: 5, grad_desc_iters: 4, start_level: 0, levels: 3, temporal_propagation: false}
- name: DIS1
  parameters: {patch_size: 13, patch_stride: 3, grad_desc_iters: 8, start_level: 0, levels: 2, temporal_propagation: false}
- name: DIS2
  parameters: {patch_size: 11, patch_stride: 3, grad_desc_iters: 8, start_level: 0, levels: 2, temporal_propagation: false}
- name: DIS3
  parameters: {patch_size: 13, patch_stride: 3, grad_desc_iters: 4, start_level: 0, levels: 2, temporal_propagation: false}
- name: DIS4
  parameters: {patch_size: 7, patch_stride: 3, grad_desc_iters: 4, start_level: 0, levels: 2, temporal_propagation: false}
- name: DIS5
  parameters: {patch_size: 5, patch_stride: 3, grad_desc_iters: 4, start_level: 0, levels: 2, temporal_propagation: false}
- name: DIS6
  parameters: {patch_size: 7, patch_stride: 4, grad_desc_iters: 4, start_level: 0, levels: 2, temporal_propagation: false}
- name: DIS7
  parameters: {patch_size: 5, patch_stride: 4, grad_desc_iters: 4, start_level: 0, levels: 2, temporal_propagation: false}
- name: DIS8
  parameters: {patch_size: 7, patch_stride: 4, grad_desc_iters: 6, start_level: 0, levels: 2, temporal_propagation: false}
- name: DIS9
  parameters: {patch_size: 7, patch_stride: 3, grad_desc_iters: 4, start_level: 0, levels: 2, temporal_propagation: false}
- name: DIS10
  parameters: {patch_size: 5, patch_stride: 3, grad_desc_iters: 4, start_level: 0, levels: 2, temporal_propagation: false}
- name: DIS11
  parameters: {patch_size: 13, patch_stride: 3, grad_desc_iters: 3, start_level: 0, levels: 2, temporal_propagation: false}
- name: DIS12
  parameters: {patch_size: 7, patch_stride: 3, grad_desc_iters: 6, start_level: 0, levels: 2, temporal_propagation: false}
- name: DIS13
  parameters: {patch_size: 9, patch_stride: 3, grad_desc_iters: 4, start_level: 0, levels: 2, temporal_propagation: false}
- name: DIS14
  parameters: {patch_size: 7, patch_stride: 4, grad_desc_iters: 4, start_level: 0, levels: 2, temporal_propagation: false}
- name: DIS15
  parameters: {patch_size: 5, patch_stride: 4, grad_desc_iters: 4, start_level: 0, levels: 2, temporal_propagation: false}
- name: DIS16
  parameters: {patch_size: 9, patch_stride: 4, grad_desc_iters: 6, start_level: 0, levels: 2, temporal_propagation: false}
- name: DIS17
  parameters: {patch_size: 7, patch_stride: 4, grad_desc_iters: 6, start_level: 0, levels: 2, temporal_propagation: false}
- name: DIS18
  parameters: {patch_size: 7, patch_stride: 5, grad_desc_iters: 5, start_level: 0, levels: 2, temporal_propagation: false}
- name: DIS19
  parameters: {patch_size: 7, patch_stride: 5, grad_desc_iters: 6, start_level: 0, levels: 2, temporal_propagation: false}
- name: DIS20
  parameters: {patch_size: 15, patch_stride: 5, grad_desc_iters: 4, start_level: 0, levels: 3, temporal_propagation: false}
- name: DIS21
  parameters: {patch_size: 17, patch_stride: 4, grad_desc_iters: 5, start_level: 0, levels: 3, temporal_propagation: false}
- name: DIS22
  parameters: {patch_size: 13, patch_stride: 4, grad_desc_iters: 4, start_level: 0, levels: 3, temporal_propagation: false}
- name: DIS23
  parameters: {patch_size: 17, patch_stride: 5, grad_desc_iters: 5, start_level: 0, levels: 3, temporal_propagation: false}
- name: DIS24
  parameters: {patch_size: 17, patch_stride: 5, grad_desc_iters: 4, start_level: 0, levels: 3, temporal_propagation: false}
- name: DIS25
  parameters: {patch_size: 17, patch_stride: 4, grad_desc_iters: 3, start_level: 0, levels: 3, temporal_propagation: false}
- name: DIS26
  parameters: {patch_size: 17, patch_stride: 4, grad_desc_iters: 4, start_level: 0, levels: 3, temporal_propagation: false}
- name: DIS27
  parameters: {patch_size: 15, patch_stride: 6, grad_desc_iters: 4, start_level: 0, levels: 3, temporal_propagation: false}
- name: DIS28
  parameters: {patch_size: 15, patch_stride: 6, grad_desc_iters: 3, start_level: 0, levels: 3, temporal_propagation: false}
- name: DIS29
  parameters: {patch_size: 15, patch_stride: 5, grad_desc_iters: 4, start_level: 0, levels: 3, temporal_propagation: false}
- name: DIS30
  parameters: {patch_size: 13, patch_stride: 4, grad_desc_iters: 4, start_level: 0, levels: 3, temporal_propagation: false}
- name: DIS31
  parameters: {patch_size: 13, patch_stride: 4, grad_desc_iters: 3, start_level: 0, levels: 3, temporal_propagation: false}
- name: DIS32
  parameters: {patch_size: 15, patch_stride: 4, grad_desc_iters: 3, start_level: 0, levels: 3, temporal_propagation: false}
- name: DIS33
  parameters: {patch_size: 15, patch_stride: 4, grad_desc_iters: 4, start_level: 0, levels: 3, temporal_propagation: false}
- name: DIS34
  parameters: {patch_size: 15, patch_stride: 4, grad_desc_iters: 5, start_level: 0, levels: 3, temporal_propagation: false}
- name: DIS35
  parameters: {patch_size: 15, patch_stride: 5, grad_desc_iters: 3, start_level: 0, levels: 3, temporal_propagation: false}
- name: DIS36
  parameters: {patch_size: 15, patch_stride: 6, grad_desc_iters: 3, start_level: 0, levels: 3, temporal_propagation: false}
- name: DIS37
  parameters: {patch_size: 15, patch_stride: 6, grad_desc_iters: 4, start_level: 0, levels: 3, temporal_propagation: false}
- name: DIS38
  parameters: {patch_size: 15, patch_stride: 6, grad_desc_iters: 5, start_level: 0, levels: 3, temporal_propagation: false}
- name: DIS39
  parameters: {patch_size: 17, patch_stride: 4, grad_desc_iters: 3, start_level: 0, levels: 3, temporal_propagation: false}
- name: DIS40
  parameters: {patch_size: 17, patch_stride: 4, grad_desc_iters: 4, start_level: 0, levels: 3, temporal_propagation: false}
- name: DIS41
  parameters: {patch_size: 17, patch_stride: 5, grad_desc_iters: 3, start_level: 0, levels: 3, temporal_propagation: false}
- name: DIS42
  parameters: {patch_size: 17, patch_stride: 5, grad_desc_iters: 3, start_level: 0, levels: 3, temporal_propagation: false}
- name: DIS43
  parameters: {patch_size: 17, patch_stride: 5, grad_desc_iters: 4, start_level: 0, levels: 3, temporal_propagation: false}
- name: DIS44
  parameters: {patch_size: 13, patch_stride: 4, grad_desc_iters: 5, start_level: 0, levels: 3, temporal_propagation: false}
- name: DIS45
  parameters: {patch_size: 13, patch_stride: 5, grad_desc_iters: 4, start_level: 0, levels: 3, temporal_propagation: false}
- name: DIS46
  parameters: {patch_size: 13, patch_stride: 5, grad_desc_iters: 4, start_level: 0, levels: 3, temporal_propagation: false}
- name: DIS47
  parameters: {patch_size: 13, patch_stride: 5, grad_desc_iters: 5, start_level: 0, levels: 3, temporal_propagation: false}
- name: DIS48
  parameters: {patch_size: 13, patch_stride: 6, grad_desc_iters: 3, start_level: 0, levels: 3, temporal_propagation: false}
- name: DIS49
  parameters: {patch_size: 13, patch_stride: 6, grad_desc_iters: 3, start_level: 0, levels: 3, temporal_propagation: false}
- name: DIS50
  parameters: {patch_size: 13, patch_stride: 6, grad_desc_iters: 4, start_level: 0, levels: 3, temporal_propagation: false}
- name: DIS51
  parameters: {patch_size: 13, patch_stride: 6, grad_desc_iters: 4, start_level: 0, levels: 3, temporal_propagation: false}
- name: DIS52
  parameters: {patch_size: 15, patch_stride: 6, grad_desc_iters: 5, start_level: 0, levels: 3, temporal_propagation: false}
